### ISSUE TITLE
Non-parallel inputs detected

### ISSUE THREAD

**Issue by rachitagrwl** [jhclark/multeval#21]
When i am trying to calculate BLEU score using multi-eval.
It is throwing me a error:

Expected 999 references, but got 500
	at multeval.HypothesisManager.loadRefs(HypothesisManager.java:66)
	at multeval.HypothesisManager.loadData(HypothesisManager.java:50)
	at multeval.MultEvalModule.run(MultEvalModule.java:109)
	at multeval.MultEval.main(MultEval.java:115)

**Comment by Star-in-Sky** [comment]
Me too！ I want to know the parameter '--hyps-baseline' . Why the example that gives 3 files.
